---
openapi: 3.0.0
info:
  title: BESTIE-Commerce API
  description: This is an E-commerce API designed for online shopping enthusiasts worldwide.
  contact:
    email: hedoris8@gmail.com
  version: 1.0.0
servers:
- url: /
tags:
- name: sellers
  description: Operations available to regular sellers
- name: customers
  description: Operations available to regular customers
paths:
  /product/create:
    post:
      tags:
      - sellers
      summary: create a new product
      description: Add a new product to the application
      operationId: app.add_new_product
      requestBody:
        description: Product to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreate'
      responses:
        "201":
          description: product created
        "400":
          description: "invalid input, object invalid"
        "409":
          description: This product already exists
  /product/review:
    post:
      tags:
      - customers
      summary: review a product
      description: Add a comment for a product to the application
      operationId: app.add_product_review
      requestBody:
        description: Product comment to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductReview'
      responses:
        "201":
          description: comment created
        "400":
          description: "invalid input, object invalid"
components:
  schemas:
    ProductCreate:
      required:
      - description
      - onsale
      - price
      - product_id
      - seller
      type: object
      properties:
        product_id:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426614174001
        seller:
          type: string
          example: Bestbuy
        price:
          type: integer
          example: 699
        onsale:
          type: boolean
          example: true
        description:
          type: string
          example: A folded e-book no need to charge.

    ProductReview:
      required:
      - comment
      - customer
      - location
      - product_id
      - rating
      - review_id
      type: object
      properties:
        review_id:
          type: string
          format: uuid
          example: f47ac10b-58cc-4372-a567-0e02b2c3d479
        product_id:
          type: string
          format: uuid
          example: 6fa459ea-ee8a-3ca4-894e-db77e160355e
        customer:
          type: string
          example: apple123123
        location:
          type: string
          example: Canada
        rating:
          type: integer
          example: 7
        comment:
          type: string
          example: product is good.
